// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcOIsf58JJhCJHTak5ULP--JqaHY__s2U',
    appId: '1:329204592665:web:79c252a23e4fe8e0107a88',
    messagingSenderId: '329204592665',
    projectId: 'proyecto-final-jtg-tienda',
    authDomain: 'proyecto-final-jtg-tienda.firebaseapp.com',
    storageBucket: 'proyecto-final-jtg-tienda.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzvHkOSaD8GEcy5TwZWvZvmKk-DrkMPTs',
    appId: '1:329204592665:android:391fb2607a67fca8107a88',
    messagingSenderId: '329204592665',
    projectId: 'proyecto-final-jtg-tienda',
    storageBucket: 'proyecto-final-jtg-tienda.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOaKrvWW1XQNAwT37Pje5p7TZKGAYoabk',
    appId: '1:329204592665:ios:24a53115a1e128e0107a88',
    messagingSenderId: '329204592665',
    projectId: 'proyecto-final-jtg-tienda',
    storageBucket: 'proyecto-final-jtg-tienda.firebasestorage.app',
    iosBundleId: 'com.example.tiendaFinalFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOaKrvWW1XQNAwT37Pje5p7TZKGAYoabk',
    appId: '1:329204592665:ios:24a53115a1e128e0107a88',
    messagingSenderId: '329204592665',
    projectId: 'proyecto-final-jtg-tienda',
    storageBucket: 'proyecto-final-jtg-tienda.firebasestorage.app',
    iosBundleId: 'com.example.tiendaFinalFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcOIsf58JJhCJHTak5ULP--JqaHY__s2U',
    appId: '1:329204592665:web:16e0cbf318d9b49b107a88',
    messagingSenderId: '329204592665',
    projectId: 'proyecto-final-jtg-tienda',
    authDomain: 'proyecto-final-jtg-tienda.firebaseapp.com',
    storageBucket: 'proyecto-final-jtg-tienda.firebasestorage.app',
  );
}
